name: timetable
description: Stundenplan

publish_to: "none"

version: 1.2.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  salomon_bottom_bar: ^3.3.1
  shared_preferences: ^2.1.0
  flutter_redux: ^0.10.0
  redux: ^5.0.0
  yaml: ^3.1.1
  webview_flutter: ^4.0.7
  html: ^0.15.2
  http: ^0.13.5
  google_fonts: ^4.0.3
  intl: ^0.17.0
  url_launcher: ^6.1.10
  firebase_crashlytics: ^3.1.0
  firebase_core: ^2.9.0
  oktoast: ^3.3.1
  markdown_widget: ^2.1.0
  pdf_render: ^1.3.8
  path_provider: ^2.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/documents/
    - pubspec.yaml
