name: timetable
description: Stundenplan

publish_to: "none"

version: 1.5.0+3

environment:
  sdk: ">=2.19.4 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  redux: ^5.0.0
  yaml: ^3.1.1
  html: ^0.15.2
  http: ^0.13.5
  google_fonts: ^4.0.3
  intl: ^0.18.0
  url_launcher: ^6.1.10
  firebase_crashlytics: ^3.1.0
  firebase_core: ^2.15.0
  oktoast: ^3.3.1
  markdown_widget: ^2.1.0
  pdf_render: ^1.3.8
  path_provider: ^2.0.14
  sqflite: ^2.2.8+2
  cupertino_icons: ^1.0.5
  salomon_bottom_bar: ^3.3.2
  shared_preferences: ^2.1.1
  flutter_redux: ^0.10.0
  path: ^1.8.3
  mutex: ^3.0.1
  flutter_inappwebview: ^5.7.2+3
  local_auth: ^2.1.6
  firebase_messaging: ^14.6.5
  flutter_local_notifications: ^15.1.0+1
  workmanager: ^0.5.1
  disable_battery_optimization: ^1.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/documents/
    - pubspec.yaml
